// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NIBRAS.Models;

#nullable disable

namespace NibrasWeb.Migrations
{
    [DbContext(typeof(NebrasdbContext))]
    [Migration("20260727183836_AddCancellationAndTariffSchema")]
    partial class AddCancellationAndTariffSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NIBRAS.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AdminReviewedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ADMIN_REVIEWED_AT");

                    b.Property<DateTime?>("AdminSignedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ADMIN_SIGNED_AT");

                    b.Property<DateTime?>("CancellationEffectiveDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CANCELLATION_EFFECTIVE_DATE");

                    b.Property<DateTime?>("CancellationRequestedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CANCELLATION_REQUESTED_AT");

                    b.Property<int?>("CancellationRequestedById")
                        .HasColumnType("int")
                        .HasColumnName("CANCELLATION_REQUESTED_BY_ID");

                    b.Property<decimal?>("CompensationAmount")
                        .HasColumnType("decimal(14, 3)")
                        .HasColumnName("COMPENSATION_AMOUNT");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("DisputeFlagged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("DISPUTE_FLAGGED");

                    b.Property<int>("InvestorId")
                        .HasColumnType("int")
                        .HasColumnName("INVESTOR_ID");

                    b.Property<decimal?>("InvestorPenaltyAmount")
                        .HasColumnType("decimal(14, 3)")
                        .HasColumnName("INVESTOR_PENALTY_AMOUNT");

                    b.Property<DateTime?>("InvestorSignedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("INVESTOR_SIGNED_AT");

                    b.Property<int>("LandId")
                        .HasColumnType("int")
                        .HasColumnName("LAND_ID");

                    b.Property<int>("LandlordId")
                        .HasColumnType("int")
                        .HasColumnName("LANDLORD_ID");

                    b.Property<DateTime?>("LandlordSignedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("LANDLORD_SIGNED_AT");

                    b.Property<int>("NoticePeriodDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(90)
                        .HasColumnName("NOTICE_PERIOD_DAYS");

                    b.Property<int>("OfferId")
                        .HasColumnType("int")
                        .HasColumnName("OFFER_ID");

                    b.Property<int?>("OfferVersionId")
                        .HasColumnType("int")
                        .HasColumnName("OFFER_VERSION_ID");

                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("STATUS_ID");

                    b.HasKey("Id")
                        .HasName("PK__CONTRACT__3214EC2738767384");

                    b.HasIndex("CancellationRequestedById");

                    b.HasIndex("InvestorId");

                    b.HasIndex("LandId");

                    b.HasIndex("LandlordId");

                    b.HasIndex("OfferVersionId");

                    b.HasIndex("StatusId");

                    b.HasIndex(new[] { "OfferId" }, "UQ__CONTRACT__96E0508AA6D26B86")
                        .IsUnique();

                    b.ToTable("CONTRACTS", (string)null);
                });

            modelBuilder.Entity("NIBRAS.Models.ContractReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("CONTRACT_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("DECISION");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("REASON");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int")
                        .HasColumnName("REVIEWER_ID");

                    b.HasKey("Id")
                        .HasName("PK__CONTRACT__3214EC273AB66E59");

                    b.HasIndex("ContractId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("CONTRACT_REVIEWS", (string)null);
                });

            modelBuilder.Entity("NIBRAS.Models.ContractStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.HasKey("Id")
                        .HasName("PK__CONTRACT__3214EC27CE14508F");

                    b.ToTable("CONTRACT_STATUSES", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "PendingSignatures"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Terminated"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rejected"
                        });
                });

            modelBuilder.Entity("NIBRAS.Models.DeletionRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminComment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ADMIN_COMMENT");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("LandId")
                        .HasColumnType("int")
                        .HasColumnName("LAND_ID");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("REASON");

                    b.Property<int>("RequestedById")
                        .HasColumnType("int")
                        .HasColumnName("REQUESTED_BY_ID");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("STATUS");

                    b.HasKey("Id")
                        .HasName("PK__DELETION__3214EC278A03ACC4");

                    b.HasIndex("LandId");

                    b.HasIndex("RequestedById");

                    b.ToTable("DELETION_REQUESTS", (string)null);
                });

            modelBuilder.Entity("NIBRAS.Models.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NAME");

                    b.HasKey("Id")
                        .HasName("PK__DOCUMENT__3214EC27579B58DC");

                    b.ToTable("DOCUMENT_TYPES", (string)null);
                });

            modelBuilder.Entity("NIBRAS.Models.Grid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CapacityMw")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("CAPACITY_MW");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NAME");

                    b.Property<int>("RegionId")
                        .HasColumnType("int")
                        .HasColumnName("REGION_ID");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("STATUS");

                    b.HasKey("Id")
                        .HasName("PK__GRIDS__3214EC27C5B24747");

                    b.HasIndex("RegionId");

                    b.ToTable("GRIDS", (string)null);
                });

            modelBuilder.Entity("NIBRAS.Models.GridCapacityReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("CONTRACT_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("GridId")
                        .HasColumnType("int")
                        .HasColumnName("GRID_ID");

                    b.Property<decimal>("ReservedMw")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("RESERVED_MW");

                    b.HasKey("Id")
                        .HasName("PK__GRID_CAP__3214EC27C682FA92");

                    b.HasIndex("GridId");

                    b.HasIndex(new[] { "ContractId" }, "UQ__GRID_CAP__3F5DFF15DEC96C5D")
                        .IsUnique();

                    b.ToTable("GRID_CAPACITY_RESERVATIONS", (string)null);
                });

            modelBuilder.Entity("NIBRAS.Models.Land", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AreaDonum")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("AREA_DONUM");

                    b.Property<bool>("DataVerifiedByAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("DATA_VERIFIED_BY_ADMIN");

                    b.Property<decimal>("DistanceToGridKm")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("DISTANCE_TO_GRID_KM");

                    b.Property<string>("DocumentStorageLocation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DOCUMENT_STORAGE_LOCATION");

                    b.Property<decimal>("ElevationM")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("ELEVATION_M");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("LandNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LAND_NUMBER");

                    b.Property<int>("LandStatusId")
                        .HasColumnType("int")
                        .HasColumnName("LAND_STATUS_ID");

                    b.Property<int>("LandlordId")
                        .HasColumnType("int")
                        .HasColumnName("LANDLORD_ID");

                    b.Property<int>("RegionId")
                        .HasColumnType("int")
                        .HasColumnName("REGION_ID");

                    b.Property<decimal>("SlopePercentage")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("SLOPE_PERCENTAGE");

                    b.Property<decimal>("SolarIrradiance")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("SOLAR_IRRADIANCE");

                    b.Property<int?>("VerifiedAgainstCriterionId")
                        .HasColumnType("int")
                        .HasColumnName("VERIFIED_AGAINST_CRITERION_ID");

                    b.HasKey("Id")
                        .HasName("PK__LANDS__3214EC278FA5F43E");

                    b.HasIndex("LandStatusId");

                    b.HasIndex("LandlordId");

                    b.HasIndex("RegionId");

                    b.HasIndex("VerifiedAgainstCriterionId");

                    b.HasIndex(new[] { "LandNumber", "RegionId" }, "UQ_LAND_NUMBER_REGION")
                        .IsUnique();

                    b.ToTable("LANDS", (string)null);
                });

            modelBuilder.Entity("NIBRAS.Models.LandCriterion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MaxGridDistanceKm")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("MAX_GRID_DISTANCE_KM");

                    b.Property<decimal>("MaxSlopePct")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("MAX_SLOPE_PCT");

                    b.Property<decimal>("MinAreaDonum")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("MIN_AREA_DONUM");

                    b.Property<decimal>("MinElevationM")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("MIN_ELEVATION_M");

                    b.Property<decimal>("MinSolarIrradiance")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("MIN_SOLAR_IRRADIANCE");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATED_AT")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("int")
                        .HasColumnName("UPDATED_BY_ID");

                    b.HasKey("Id")
                        .HasName("PK__LAND_CRI__3214EC276031D9CC");

                    b.HasIndex("UpdatedById");

                    b.ToTable("LAND_CRITERIA", (string)null);
                });

            modelBuilder.Entity("NIBRAS.Models.LandDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("DOCUMENT_TYPE_ID");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("FILE_PATH");

                    b.Property<int>("LandId")
                        .HasColumnType("int")
                        .HasColumnName("LAND_ID");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("STATUS");

                    b.Property<DateTime?>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("UPLOADED_AT")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("VERSION");

                    b.HasKey("Id")
                        .HasName("PK__LAND_DOC__3214EC27A38FC9A9");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("LandId");

                    b.ToTable("LAND_DOCUMENTS", (string)null);
                });

            modelBuilder.Entity("NIBRAS.Models.LandStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.HasKey("Id")
                        .HasName("PK__LAND_STA__3214EC27D4FB7967");

                    b.ToTable("LAND_STATUSES", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Draft"
                        },
                        new
                        {
                            Id = 2,
                            Name = "PendingVerification"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Verified"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rejected"
                        });
                });

            modelBuilder.Entity("NIBRAS.Models.LandStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CHANGED_AT")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ChangedById")
                        .HasColumnType("int")
                        .HasColumnName("CHANGED_BY_ID");

                    b.Property<int>("LandId")
                        .HasColumnType("int")
                        .HasColumnName("LAND_ID");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("REASON");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("STATUS_ID");

                    b.HasKey("Id")
                        .HasName("PK__LAND_STA__3214EC27F466086B");

                    b.HasIndex("ChangedById");

                    b.HasIndex("LandId");

                    b.ToTable("LAND_STATUS_HISTORY", (string)null);
                });

            modelBuilder.Entity("NIBRAS.Models.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AcceptedVersionId")
                        .HasColumnType("int")
                        .HasColumnName("ACCEPTED_VERSION_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("InvestorId")
                        .HasColumnType("int")
                        .HasColumnName("INVESTOR_ID");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED");

                    b.Property<int>("LandId")
                        .HasColumnType("int")
                        .HasColumnName("LAND_ID");

                    b.Property<decimal>("RequiredCapacityMw")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("REQUIRED_CAPACITY_MW");

                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("STATUS_ID");

                    b.HasKey("Id")
                        .HasName("PK__OFFERS__3214EC277FE0E225");

                    b.HasIndex("AcceptedVersionId");

                    b.HasIndex("InvestorId");

                    b.HasIndex("LandId");

                    b.HasIndex("StatusId");

                    b.ToTable("OFFERS", (string)null);
                });

            modelBuilder.Entity("NIBRAS.Models.OfferStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.HasKey("Id")
                        .HasName("PK__OFFER_ST__3214EC27D14BDC1A");

                    b.ToTable("OFFER_STATUSES", (string)null);
                });

            modelBuilder.Entity("NIBRAS.Models.OfferVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int")
                        .HasColumnName("CREATED_BY_ID");

                    b.Property<int?>("DurationYears")
                        .HasColumnType("int")
                        .HasColumnName("DURATION_YEARS");

                    b.Property<decimal?>("EffectiveCostPerKw")
                        .HasColumnType("decimal(10, 3)")
                        .HasColumnName("EFFECTIVE_COST_PER_KWH");

                    b.Property<decimal?>("ExpectedAnnualRevenue")
                        .HasColumnType("decimal(14, 3)")
                        .HasColumnName("EXPECTED_ANNUAL_REVENUE");

                    b.Property<decimal?>("InstallationCost")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("INSTALLATION_COST");

                    b.Property<decimal?>("LandlordSharePct")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("LANDLORD_SHARE_PCT");

                    b.Property<int>("OfferId")
                        .HasColumnType("int")
                        .HasColumnName("OFFER_ID");

                    b.Property<decimal?>("PaybackPeriodMonths")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("PAYBACK_PERIOD_MONTHS");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("REJECTION_REASON");

                    b.Property<decimal?>("SolarCellCapacityKw")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("SOLAR_CELL_CAPACITY_KW");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("START_DATE");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int")
                        .HasColumnName("VERSION_NUMBER");

                    b.HasKey("Id")
                        .HasName("PK__OFFER_VE__3214EC27145811E1");

                    b.HasIndex("CreatedById");

                    b.HasIndex("OfferId");

                    b.ToTable("OFFER_VERSIONS", (string)null);
                });

            modelBuilder.Entity("NIBRAS.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("LossPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("LOSS_PERCENTAGE");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NAME_AR");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NAME_EN");

                    b.Property<decimal>("PeakSunHoursPerDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(5.5m)
                        .HasColumnName("PEAK_SUN_HOURS_PER_DAY");

                    b.Property<decimal>("WheelingFeePerKwh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 3)")
                        .HasDefaultValue(0m)
                        .HasColumnName("WHEELING_FEE_PER_KWH");

                    b.HasKey("Id")
                        .HasName("PK__REGIONS__3214EC27BEC00DCF");

                    b.ToTable("REGIONS", (string)null);
                });

            modelBuilder.Entity("NIBRAS.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.HasKey("Id")
                        .HasName("PK__ROLES__3214EC276782D7D4");

                    b.ToTable("ROLES", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Landlord"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Investor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 4,
                            Name = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("NIBRAS.Models.TariffBracket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2")
                        .HasColumnName("EFFECTIVE_FROM");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2")
                        .HasColumnName("EFFECTIVE_TO");

                    b.Property<int>("FromKwh")
                        .HasColumnType("int")
                        .HasColumnName("FROM_KWH");

                    b.Property<decimal>("RatePerKwh")
                        .HasColumnType("decimal(10, 3)")
                        .HasColumnName("RATE_PER_KWH");

                    b.Property<int>("RegionId")
                        .HasColumnType("int")
                        .HasColumnName("REGION_ID");

                    b.Property<int?>("ToKwh")
                        .HasColumnType("int")
                        .HasColumnName("TO_KWH");

                    b.HasKey("Id")
                        .HasName("PK__TARIFF_BRACKETS");

                    b.HasIndex("RegionId");

                    b.ToTable("TARIFF_BRACKETS", (string)null);
                });

            modelBuilder.Entity("NIBRAS.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DatefoBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FULL_NAME");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PASSWORD_HASH");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PHONE");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("ROLE_ID");

                    b.HasKey("Id")
                        .HasName("PK__USERS__3214EC27D0F84BA1");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__USERS__161CF724F5C148C0")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "UQ__USERS__D4FA0A2658412415")
                        .IsUnique();

                    b.ToTable("USERS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "system@nibras.internal",
                            FullName = "System",
                            IsDeleted = false,
                            PasswordHash = "N/A",
                            Phone = "0000000000",
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("NIBRAS.Models.Contract", b =>
                {
                    b.HasOne("NIBRAS.Models.User", "CancellationRequestedBy")
                        .WithMany("CancellationRequestedContracts")
                        .HasForeignKey("CancellationRequestedById")
                        .HasConstraintName("FK_CONTRACTS_CANCELLATION_REQUESTER");

                    b.HasOne("NIBRAS.Models.User", "Investor")
                        .WithMany("ContractInvestors")
                        .HasForeignKey("InvestorId")
                        .IsRequired()
                        .HasConstraintName("FK_CONTRACTS_INVESTORS");

                    b.HasOne("NIBRAS.Models.Land", "Land")
                        .WithMany("Contracts")
                        .HasForeignKey("LandId")
                        .IsRequired()
                        .HasConstraintName("FK_CONTRACTS_LANDS");

                    b.HasOne("NIBRAS.Models.User", "Landlord")
                        .WithMany("ContractLandlords")
                        .HasForeignKey("LandlordId")
                        .IsRequired()
                        .HasConstraintName("FK_CONTRACTS_LANDLORDS");

                    b.HasOne("NIBRAS.Models.Offer", "Offer")
                        .WithOne("Contract")
                        .HasForeignKey("NIBRAS.Models.Contract", "OfferId")
                        .IsRequired()
                        .HasConstraintName("FK_CONTRACTS_OFFERS");

                    b.HasOne("NIBRAS.Models.OfferVersion", "OfferVersion")
                        .WithMany()
                        .HasForeignKey("OfferVersionId")
                        .HasConstraintName("FK_CONTRACTS_OFFER_VERSION");

                    b.HasOne("NIBRAS.Models.ContractStatus", "Status")
                        .WithMany("Contracts")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_CONTRACTS_STATUS");

                    b.Navigation("CancellationRequestedBy");

                    b.Navigation("Investor");

                    b.Navigation("Land");

                    b.Navigation("Landlord");

                    b.Navigation("Offer");

                    b.Navigation("OfferVersion");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("NIBRAS.Models.ContractReview", b =>
                {
                    b.HasOne("NIBRAS.Models.Contract", "Contract")
                        .WithMany("ContractReviews")
                        .HasForeignKey("ContractId")
                        .IsRequired()
                        .HasConstraintName("FK_CR_CONTRACTS");

                    b.HasOne("NIBRAS.Models.User", "Reviewer")
                        .WithMany("ContractReviews")
                        .HasForeignKey("ReviewerId")
                        .IsRequired()
                        .HasConstraintName("FK_CR_USERS");

                    b.Navigation("Contract");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("NIBRAS.Models.DeletionRequest", b =>
                {
                    b.HasOne("NIBRAS.Models.Land", "Land")
                        .WithMany("DeletionRequests")
                        .HasForeignKey("LandId")
                        .IsRequired()
                        .HasConstraintName("FK_DELETION_LANDS");

                    b.HasOne("NIBRAS.Models.User", "RequestedBy")
                        .WithMany("DeletionRequests")
                        .HasForeignKey("RequestedById")
                        .IsRequired()
                        .HasConstraintName("FK_DELETION_USERS");

                    b.Navigation("Land");

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("NIBRAS.Models.Grid", b =>
                {
                    b.HasOne("NIBRAS.Models.Region", "Region")
                        .WithMany("Grids")
                        .HasForeignKey("RegionId")
                        .IsRequired()
                        .HasConstraintName("FK_GRIDS_REGIONS");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("NIBRAS.Models.GridCapacityReservation", b =>
                {
                    b.HasOne("NIBRAS.Models.Contract", "Contract")
                        .WithOne("GridCapacityReservation")
                        .HasForeignKey("NIBRAS.Models.GridCapacityReservation", "ContractId")
                        .IsRequired()
                        .HasConstraintName("FK_GCR_CONTRACTS");

                    b.HasOne("NIBRAS.Models.Grid", "Grid")
                        .WithMany("GridCapacityReservations")
                        .HasForeignKey("GridId")
                        .IsRequired()
                        .HasConstraintName("FK_GCR_GRIDS");

                    b.Navigation("Contract");

                    b.Navigation("Grid");
                });

            modelBuilder.Entity("NIBRAS.Models.Land", b =>
                {
                    b.HasOne("NIBRAS.Models.LandStatus", "LandStatus")
                        .WithMany("Lands")
                        .HasForeignKey("LandStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_LANDS_STATUS");

                    b.HasOne("NIBRAS.Models.User", "Landlord")
                        .WithMany("Lands")
                        .HasForeignKey("LandlordId")
                        .IsRequired()
                        .HasConstraintName("FK_LANDS_LANDLORDS");

                    b.HasOne("NIBRAS.Models.Region", "Region")
                        .WithMany("Lands")
                        .HasForeignKey("RegionId")
                        .IsRequired()
                        .HasConstraintName("FK_LANDS_REGIONS");

                    b.HasOne("NIBRAS.Models.LandCriterion", "VerifiedAgainstCriterion")
                        .WithMany()
                        .HasForeignKey("VerifiedAgainstCriterionId")
                        .HasConstraintName("FK_LANDS_VERIFIED_CRITERION");

                    b.Navigation("LandStatus");

                    b.Navigation("Landlord");

                    b.Navigation("Region");

                    b.Navigation("VerifiedAgainstCriterion");
                });

            modelBuilder.Entity("NIBRAS.Models.LandCriterion", b =>
                {
                    b.HasOne("NIBRAS.Models.User", "UpdatedBy")
                        .WithMany("LandCriteria")
                        .HasForeignKey("UpdatedById")
                        .IsRequired()
                        .HasConstraintName("FK_LC_USERS");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("NIBRAS.Models.LandDocument", b =>
                {
                    b.HasOne("NIBRAS.Models.DocumentType", "DocumentType")
                        .WithMany("LandDocuments")
                        .HasForeignKey("DocumentTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_LD_DOCTYPES");

                    b.HasOne("NIBRAS.Models.Land", "Land")
                        .WithMany("LandDocuments")
                        .HasForeignKey("LandId")
                        .IsRequired()
                        .HasConstraintName("FK_LD_LANDS");

                    b.Navigation("DocumentType");

                    b.Navigation("Land");
                });

            modelBuilder.Entity("NIBRAS.Models.LandStatusHistory", b =>
                {
                    b.HasOne("NIBRAS.Models.User", "ChangedBy")
                        .WithMany("LandStatusHistories")
                        .HasForeignKey("ChangedById")
                        .IsRequired()
                        .HasConstraintName("FK_LSH_USERS");

                    b.HasOne("NIBRAS.Models.Land", "Land")
                        .WithMany("LandStatusHistories")
                        .HasForeignKey("LandId")
                        .IsRequired()
                        .HasConstraintName("FK_LSH_LANDS");

                    b.Navigation("ChangedBy");

                    b.Navigation("Land");
                });

            modelBuilder.Entity("NIBRAS.Models.Offer", b =>
                {
                    b.HasOne("NIBRAS.Models.OfferVersion", "AcceptedVersion")
                        .WithMany()
                        .HasForeignKey("AcceptedVersionId")
                        .HasConstraintName("FK_OFFERS_ACCEPTED_VERSION");

                    b.HasOne("NIBRAS.Models.User", "Investor")
                        .WithMany("Offers")
                        .HasForeignKey("InvestorId")
                        .IsRequired()
                        .HasConstraintName("FK_OFFERS_INVESTORS");

                    b.HasOne("NIBRAS.Models.Land", "Land")
                        .WithMany("Offers")
                        .HasForeignKey("LandId")
                        .IsRequired()
                        .HasConstraintName("FK_OFFERS_LANDS");

                    b.HasOne("NIBRAS.Models.OfferStatus", "Status")
                        .WithMany("Offers")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_OFFERS_STATUS");

                    b.Navigation("AcceptedVersion");

                    b.Navigation("Investor");

                    b.Navigation("Land");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("NIBRAS.Models.OfferVersion", b =>
                {
                    b.HasOne("NIBRAS.Models.User", "CreatedBy")
                        .WithMany("OfferVersions")
                        .HasForeignKey("CreatedById")
                        .IsRequired()
                        .HasConstraintName("FK_OV_USERS");

                    b.HasOne("NIBRAS.Models.Offer", "Offer")
                        .WithMany("OfferVersions")
                        .HasForeignKey("OfferId")
                        .IsRequired()
                        .HasConstraintName("FK_OV_OFFERS");

                    b.Navigation("CreatedBy");

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("NIBRAS.Models.TariffBracket", b =>
                {
                    b.HasOne("NIBRAS.Models.Region", "Region")
                        .WithMany("TariffBrackets")
                        .HasForeignKey("RegionId")
                        .IsRequired()
                        .HasConstraintName("FK_TB_REGIONS");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("NIBRAS.Models.User", b =>
                {
                    b.HasOne("NIBRAS.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_USERS_ROLES");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NIBRAS.Models.Contract", b =>
                {
                    b.Navigation("ContractReviews");

                    b.Navigation("GridCapacityReservation");
                });

            modelBuilder.Entity("NIBRAS.Models.ContractStatus", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("NIBRAS.Models.DocumentType", b =>
                {
                    b.Navigation("LandDocuments");
                });

            modelBuilder.Entity("NIBRAS.Models.Grid", b =>
                {
                    b.Navigation("GridCapacityReservations");
                });

            modelBuilder.Entity("NIBRAS.Models.Land", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("DeletionRequests");

                    b.Navigation("LandDocuments");

                    b.Navigation("LandStatusHistories");

                    b.Navigation("Offers");
                });

            modelBuilder.Entity("NIBRAS.Models.LandStatus", b =>
                {
                    b.Navigation("Lands");
                });

            modelBuilder.Entity("NIBRAS.Models.Offer", b =>
                {
                    b.Navigation("Contract");

                    b.Navigation("OfferVersions");
                });

            modelBuilder.Entity("NIBRAS.Models.OfferStatus", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("NIBRAS.Models.Region", b =>
                {
                    b.Navigation("Grids");

                    b.Navigation("Lands");

                    b.Navigation("TariffBrackets");
                });

            modelBuilder.Entity("NIBRAS.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("NIBRAS.Models.User", b =>
                {
                    b.Navigation("CancellationRequestedContracts");

                    b.Navigation("ContractInvestors");

                    b.Navigation("ContractLandlords");

                    b.Navigation("ContractReviews");

                    b.Navigation("DeletionRequests");

                    b.Navigation("LandCriteria");

                    b.Navigation("LandStatusHistories");

                    b.Navigation("Lands");

                    b.Navigation("OfferVersions");

                    b.Navigation("Offers");
                });
#pragma warning restore 612, 618
        }
    }
}
